
(() => {
'use strict';
const VERSION='v0.12.0_corridor';
const canvas=document.getElementById('gameCanvas');
if(!canvas){console.error('gameCanvas not found');return;}
const ctx=canvas.getContext('2d');
const DPR_MAX=2, STORAGE_KEY='next_room_v01200_corridor_save';
const ASSET_BASES=['','assets/','images/'];
const GHOSTS=[
{name:'猼訑',nameEn:'Botuo',file:'猼訑.png',type:'normal',speed:1.28,fire:2,desc:'警觉又狡猾，喜欢躲在门后观察人。',descEn:'Alert and cunning. It likes watching people from behind the door.'},
{name:'赤鱬',nameEn:'Chiru',file:'赤鱬.png',type:'thin',speed:2.08,fire:2,desc:'细长灵活，动作很快，最擅长突然贴近。',descEn:'Slim, agile, and fast. It is good at suddenly closing the distance.'},
{name:'当康',nameEn:'Dangkang',file:'当康.png',type:'heavy',speed:1.05,fire:2,desc:'体型敦实，压迫感强，逼近时像重物挪动。',descEn:'Heavy and solid. Its approach feels like something massive shifting forward.'},
{name:'混沌',nameEn:'Hundun',file:'混沌.png',type:'heavy',speed:.72,fire:3,desc:'轮廓混乱，越盯着看越分不清它的形状。',descEn:'A chaotic silhouette. The longer you stare, the harder it is to read.'},
{name:'九尾狐',nameEn:'Nine-tailed Fox',file:'九尾狐.png',type:'normal',speed:1.76,fire:2,ghostEye:true,desc:'擅长迷惑视线，被封印后会短暂开启鬼眼。',descEn:'A master of deception. Sealing it briefly activates Ghost Eye.'},
{name:'夔牛',nameEn:'Kui Ox',file:'夔牛.png',type:'heavy',speed:1.18,fire:2,desc:'独脚震地，虽然不快，但每次靠近都很有压迫。',descEn:'Not the fastest, but every step feels heavy and oppressive.'},
{name:'麒麟',nameEn:'Qilin',file:'麒麟.png',type:'normal',speed:1.42,fire:2,desc:'外表庄重，但在门后出现时往往并不吉利。',descEn:'It looks solemn, but seeing it behind the door is never a good sign.'},
{name:'穷奇',nameEn:'Qiongqi',file:'穷奇.png',type:'thin',speed:2.22,fire:3,desc:'凶性外露，判断失误时最容易被它扑出门。',descEn:'Ferocious and direct. One bad read can let it burst out.'},
{name:'饕餮',nameEn:'Taotie',file:'饕餮.png',type:'heavy',speed:1.32,fire:3,desc:'贪婪巨口，虽然笨重，但存在感异常强烈。',descEn:'A greedy maw. Slow and heavy, but impossible to ignore.'},
{name:'狰',nameEn:'Zheng',file:'狰.png',type:'normal',speed:1.70,fire:3,desc:'神情凶狠，常常伴着成群鬼火一起出现。',descEn:'A fierce presence, often surrounded by ghost fire.'},
{name:'烛阴',nameEn:'Zhuyin',file:'烛阴.png',type:'thin',speed:2.45,fire:3,desc:'危险等级极高，速度极快，几乎不给人反应时间。',descEn:'Extremely dangerous and very fast. It gives you almost no time to react.'}
];
const PEOPLE=[
{name:'1号人物',nameEn:'Resident 1',file:'1号人物.png',scale:1.28,desc:'一个看起来有点拘谨的普通住客。',descEn:'A slightly awkward but ordinary resident.'},
{name:'2号人物',nameEn:'Resident 2',file:'2号人物.png',desc:'总像在发呆，但目前没有发现异常。',descEn:'Often looks spaced out, but no anomaly has been found.'},
{name:'3号人物',nameEn:'Resident 3',file:'3号人物.png',desc:'动作有点夸张，容易让人误以为是鬼。',descEn:'Moves dramatically, which makes them easy to misjudge.'},
{name:'4号人物',nameEn:'Resident 4',file:'4号人物.png',desc:'门后最常见的住客之一，神态比较平静。',descEn:'One of the more common residents behind the door.'},
{name:'5号人物',nameEn:'Resident 5',file:'5号人物.png',desc:'经常保持奇怪姿势，但本质上只是普通人。',descEn:'Often caught in odd poses, but still a normal person.'},
{name:'6号人物',nameEn:'Resident 6',file:'6号人物.png',desc:'喜欢独自待着，容易制造出尴尬气氛。',descEn:'Likes being alone and often creates awkward scenes.'},
{name:'7号人物',nameEn:'Resident 7',file:'7号人物.png',desc:'看起来心事重重，常常在角落停留。',descEn:'Looks troubled and often stays in the corner.'},
{name:'8号人物',nameEn:'Resident 8',file:'8号人物.png',desc:'表情有点空，但目前还算安全。',descEn:'A blank expression, but currently considered safe.'},
{name:'9号人物',nameEn:'Resident 9',file:'9号人物.png',desc:'动作松弛，属于让人放松警惕的类型。',descEn:'Relaxed and harmless-looking, which can lower your guard.'},
{name:'10号人物',nameEn:'Resident 10',file:'10号人物.png',desc:'气质最怪的一位普通住客，最容易被误封。',descEn:'The strangest-looking resident, and the easiest to seal by mistake.'}
];
const FIRE=['鬼火1.png','鬼火2.png','鬼火3.png','鬼火4.png','鬼火5.png'];
const BOSSES=[{stage:1,time:7,seals:16},{stage:2,time:6.5,seals:20},{stage:3,time:6,seals:24},{stage:4,time:5.8,seals:28},{stage:5,time:5.5,seals:30}];
function loadSave(){try{let raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem('next_room_v01111_save');if(!raw)throw 0;let d=JSON.parse(raw);return{bestRoom:+(d.bestRoom||1),ghosts:d.ghosts||{},people:d.people||{}}}catch(e){return{bestRoom:1,ghosts:{},people:{}}}}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(S.save))}catch(e){}}
const S={screen:'menu',lang:'zh',lastScreen:'menu',difficulty:'normal',room:1,mode:'normal',content:null,nextContent:null,door:0,snapTarget:null,dragging:false,dragX:0,dragDoor:0,danger:0,sealFlash:0,transition:0,corridorOffset:0,pendingNextRoom:2,resultReason:'',ghostEye:0,eyeFx:0,bossDefeated:{},toast:null,galleryTab:'ghosts',galleryScroll:0,galleryDragging:false,galleryY:0,galleryStart:0,rulesScroll:0,rulesDragging:false,rulesY:0,rulesStart:0,loadingFiles:[],loadingElapsed:0,loadingNextScreen:'menu',layout:null,pointer:{x:0,y:0,down:false},pressed:null,save:loadSave(),t:0};
const assets={}, cache={};
function cand(file){const out=[];ASSET_BASES.forEach(b=>{let s=b+file;if(!out.includes(s))out.push(s);let e=encodeURI(s);if(e!==s&&!out.includes(e))out.push(e)});return out}
function loadImg(file){if(cache[file]&&cache[file].started)return cache[file];let r={started:true,loaded:false,failed:false,img:null,i:0,c:cand(file)};cache[file]=r;function next(){if(r.loaded)return;if(r.i>=r.c.length){r.failed=true;assets[file]=null;return}let img=new Image();img.decoding='async';let src=r.c[r.i++];img.onload=()=>{if(r.loaded)return;r.loaded=true;r.failed=false;r.img=img;assets[file]=img};img.onerror=next;img.src=src}next();return r}
function img(file){let r=cache[file]||loadImg(file);if(r.loaded&&r.img&&r.img.complete&&r.img.naturalWidth)return r.img;let a=assets[file];if(a&&a.complete&&a.naturalWidth)return a;return null}
['封印按钮.png',...FIRE].forEach(loadImg);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t, rand=a=>a[Math.floor(Math.random()*a.length)], ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
const en=()=>S.lang==='en', ui=(z,e)=>en()?e:z, nm=o=>en()?(o.nameEn||o.name):o.name, ds=o=>en()?(o.descEn||o.desc||'No record yet.'):(o.desc||'暂无记录');
function resize(){let dpr=Math.min(window.devicePixelRatio||1,DPR_MAX),w=Math.max(320,innerWidth||390),h=Math.max(520,innerHeight||760);canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);S.layout=layout(w,h)}
function layout(w,h){let topH=Math.max(82,Math.min(100,h*.108)),bottomH=Math.max(112,Math.min(138,h*.15)),gameTop=topH,gameBottom=h-bottomH,gameH=gameBottom-gameTop;let dh=clamp(Math.min(gameH*.82,w*1.34,620),370,620),dw=dh*.62,dx=(w-dw)/2,dy=gameTop+Math.max(22,(gameH-dh)*.42);let door={x:dx,y:dy,w:dw,h:dh};return{w,h,topH,bottomH,gameTop,gameBottom,gameH,door,hole:{...door},home:{x:10,y:18,w:64,h:36},galleryButton:{x:w-86,y:18,w:76,h:36},sealButton:{x:w/2-88,y:h-124,w:176,h:82},bossButton:{x:w/2-132,y:h-118,w:264,h:76}}}
addEventListener('resize',resize);resize();
function uniq(a){return[...new Set((a||[]).filter(Boolean))]}function preload(a){uniq(a).forEach(loadImg)}
function initialFiles(){return uniq(['封印按钮.png',...FIRE,...PEOPLE.slice(0,4).map(p=>p.file),...GHOSTS.slice(0,5).map(g=>g.file)])}
function progress(files){let l=uniq(files);if(!l.length)return{loaded:1,count:0,total:0};let c=0;l.forEach(f=>{let im=img(f);if(im)c++});return{loaded:c/l.length,count:c,total:l.length}}
function cFiles(c){if(!c)return['封印按钮.png',...FIRE];let f=['封印按钮.png'];if(c.type==='ghost'){c.ghosts.forEach(g=>f.push(g.file));f.push(...FIRE.slice(0,3))}else if(c.type==='person')f.push(c.person.file);else if(c.type==='boss')f.push(c.bossGhost.file,...FIRE);else f.push(...FIRE.slice(0,2));return uniq(f)}
function stageFiles(room=S.room){let n=clamp(4+Math.floor(room/8),4,GHOSTS.length),st=bossStage(room);return uniq(['封印按钮.png',...FIRE,...PEOPLE.map(p=>p.file),...GHOSTS.slice(0,Math.min(GHOSTS.length,n+2)).map(g=>g.file),bossGhost(st).file])}
function beginLoading(next,files){S.screen='loading';S.loadingNextScreen=next;S.loadingFiles=uniq(files);S.loadingElapsed=0;preload(S.loadingFiles)}
function bossStage(r){return Math.floor((r-1)/25)+1}function bossWin(r){let stage=bossStage(r),end=stage*25,start=end-5;return{stage,start,end,forced:r===end,active:r>=start&&r<=end}}
function bossCfg(s){return BOSSES[Math.min(s,BOSSES.length)-1]||{stage:s,time:5.5,seals:30}}function bossGhost(s){return GHOSTS[(s*2+6)%GHOSTS.length]}
function prog(){let stage=bossStage(S.room),index=((S.room-1)%25)+1;return{stage,index,ratio:index/25,boss:bossGhost(stage)}}
function gSpeed(g){return(g.speed||1)*(g.type==='thin'?1.18:g.type==='heavy'?.92:1)}
function approach(){let raw=clamp(S.danger,0,1),steps=7,i=Math.floor(raw*steps),local=raw*steps-i,kick=Math.sin(local*Math.PI)*.055;return clamp(i/steps+kick,0,1)}
function ghostCount(r){if(r<25)return 1;if(r<50)return Math.random()<.34?2:1;let x=Math.random();return x<.22?3:x<.58?2:1}
function pickGhosts(n,r){let u=clamp(4+Math.floor(r/8),4,GHOSTS.length),pool=GHOSTS.slice(0,u),out=[];while(out.length<n){let g=rand(pool);if(!out.includes(g))out.push(g)}return out}
function makeContent(room){let w=bossWin(room);if(w.active&&!S.bossDefeated[w.stage]){let chance=w.forced?1:(.26+(room-w.start)*.11);if(Math.random()<chance){let bg=bossGhost(w.stage);return{type:'boss',stage:w.stage,bossGhost:bg,cfg:bossCfg(w.stage),seen:false,bossSeen:false,hits:0,talismans:[],forced:w.forced,passTimer:0}}}let r=Math.random(),gc=clamp(.44+room*.004,.44,.72),pc=room<8?.34:.28;if(r<gc){let n=ghostCount(room);return{type:'ghost',ghosts:pickGhosts(n,room),requiredSeals:n,sealed:0,seen:false,passTimer:0,talismans:[]}}if(r<gc+pc)return{type:'person',person:rand(PEOPLE),seen:false,passTimer:0,talismans:[]};return{type:'empty',seen:false,passTimer:0,talismans:[]}}
function createContent(){S.mode='normal';S.door=0;S.snapTarget=null;S.dragging=false;S.danger=0;S.sealFlash=0;S.transition=0;S.corridorOffset=0;S.content=makeContent(S.room);preload([...cFiles(S.content),...stageFiles(S.room).slice(0,8)])}
function startRun(d){S.screen='game';S.difficulty=d;S.room=1;S.mode='normal';S.door=0;S.snapTarget=null;S.dragging=false;S.danger=0;S.sealFlash=0;S.transition=0;S.corridorOffset=0;S.pendingNextRoom=2;S.resultReason='';S.ghostEye=0;S.eyeFx=0;S.bossDefeated={};S.toast=null;createContent()}
function seen(){let c=S.content;if(!c||c.seen)return;c.seen=true;if(c.type==='ghost')c.ghosts.forEach(g=>S.save.ghosts[g.name]=true);else if(c.type==='person')S.save.people[c.person.name]=true;else if(c.type==='boss')S.save.ghosts[c.bossGhost.name]=true;save()}
function toast(t,time=1.4){S.toast={text:t,time}}
function startAdvance(o={}){S.mode='corridorTransition';S.transition=0;S.corridorOffset=0;S.pendingNextRoom=o.toRoom||S.room+1;S.nextContent=makeContent(S.pendingNextRoom);preload([...cFiles(S.nextContent),...stageFiles(S.pendingNextRoom).slice(0,8)]);S.dragging=false;S.snapTarget=null;S.danger=0;S.save.bestRoom=Math.max(S.save.bestRoom||1,S.pendingNextRoom);save()}
function finishAdvance(){S.room=S.pendingNextRoom;S.content=S.nextContent;S.nextContent=null;S.mode='normal';S.transition=0;S.corridorOffset=0;S.door=0;S.snapTarget=null;S.dragging=false;S.danger=0;S.sealFlash=0}
function gameOver(r){S.resultReason=r;S.save.bestRoom=Math.max(S.save.bestRoom||1,S.room);save();S.screen='result';S.mode='normal';S.dragging=false;S.snapTarget=null}
function beginBoss(){S.mode='bossFight';S.door=.06;S.snapTarget=null;S.danger=0;toast('Boss开始顶门！',1.1)}
function update(dt){S.t+=dt;if(S.toast){S.toast.time-=dt;if(S.toast.time<=0)S.toast=null}if(S.ghostEye>0&&S.screen==='game')S.ghostEye=Math.max(0,S.ghostEye-dt);if(S.eyeFx>0&&S.screen==='game')S.eyeFx=Math.max(0,S.eyeFx-dt);if(S.screen==='loading'){S.loadingElapsed+=dt;let p=progress(S.loadingFiles).loaded;if(S.loadingElapsed>.55&&(p>=1||S.loadingElapsed>2.5)){S.screen=S.loadingNextScreen;S.loadingFiles=[]}return}if(S.screen!=='game')return;if(S.mode==='corridorTransition'){S.transition+=dt*2.7;S.corridorOffset=-S.layout.w*ease(clamp(S.transition,0,1));if(S.transition>=1)finishAdvance();return}if(S.mode==='sealSuccess'){S.sealFlash+=dt;if(S.sealFlash>=.62){if(S.content&&S.content.talismans)S.content.talismans=[];startAdvance({toRoom:S.pendingNextRoom||S.room+1})}return}if(S.snapTarget!==null&&!S.dragging&&S.mode==='normal'){let dir=S.snapTarget>S.door?1:-1,spd=S.difficulty==='normal'?2.85:2.2;S.door+=dir*spd*dt;if((dir>0&&S.door>=S.snapTarget)||(dir<0&&S.door<=S.snapTarget)){S.door=S.snapTarget;S.snapTarget=null}S.door=clamp(S.door,0,1)}let c=S.content;if(!c)return;if(S.door>.08)seen();if(S.mode==='bossFight'){let hp=1-c.hits/c.cfg.seals,boost=hp<.3?1.25:1.08,hard=S.difficulty==='normal'?1.22:1;S.door+=dt/c.cfg.time*boost*hard;S.door=clamp(S.door,0,1);if(S.door>=1){if(c.forced)gameOver('强制Boss战失败，Boss冲出来了');else{toast('Boss逃走了',1.1);startAdvance({toRoom:S.room+1})}}return}if(c.type==='ghost'){if(S.door>.055){let base=.62+Math.min(S.room,90)*.0066,fast=Math.max(...c.ghosts.map(gSpeed)),multi=1+(c.ghosts.length-1)*.34,easy=S.difficulty==='easy'&&c.ghosts.some(g=>g.type==='thin')?.92:1,hard=S.difficulty==='normal'?1.38:1,open=.95+S.door*1.05;S.danger+=dt*base*fast*multi*easy*hard*open}else S.danger=0;if(S.danger>=1)gameOver('门开太久，鬼冲出来了')}else if(c.type==='person'||c.type==='empty'){if(S.door>=.92){c.passTimer+=dt;if(c.passTimer>.06)startAdvance({toRoom:S.room+1})}else c.passTimer=0}else if(c.type==='boss'){if(S.door>.12)c.bossSeen=true;if(c.bossSeen&&S.door<.04&&!S.dragging&&S.snapTarget===null)beginBoss()}}
function sealClick(){if(S.screen!=='game'||S.mode!=='normal')return;let c=S.content;if(!c)return;if(c.type==='person')return gameOver('封错了，人家只是普通人');if(c.type==='empty')return gameOver('封错了，这间房是空的');if(c.type==='boss')return toast(c.bossSeen?'关门后才能开始贴符':'先开门确认');if(c.type!=='ghost')return;if(S.door>.08)return toast('先把门关上');c.sealed++;c.talismans.push(talisman());S.sealFlash=.01;if(c.sealed>=c.requiredSeals){c.ghosts.forEach(g=>{if(g.ghostEye){S.ghostEye=10;S.eyeFx=1.05;toast('鬼眼开启：10秒透视',1.6)}});S.mode='sealSuccess';S.pendingNextRoom=S.room+1;S.snapTarget=null}else toast('符咒贴上去了')}
function bossSeal(){let c=S.content;if(!c||c.type!=='boss'||S.mode!=='bossFight')return;c.hits++;c.talismans.push(talisman());S.door=Math.max(0,S.door-.13);S.sealFlash=.01;if(c.hits>=c.cfg.seals){S.bossDefeated[c.stage]=true;S.pendingNextRoom=c.stage*25+1;S.mode='sealSuccess';S.sealFlash=.01;toast('Boss已封印，进入下一大关',1.4)}}
function talisman(){return{rx:.18+Math.random()*.64,ry:.14+Math.random()*.68,rot:(Math.random()-.5)*.7,scale:.72+Math.random()*.38,born:S.t}}
function ptr(e){let r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}function hit(p,r){return p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h}function inf(r,x,y=x){return{x:r.x-x,y:r.y-y,w:r.w+x*2,h:r.h+y*2}}function press(id,r){S.pressed={id,r,t:S.t}}function isPress(id){return S.pointer.down&&S.pressed&&S.pressed.id===id}
function down(e){e.preventDefault();let p=ptr(e);S.pointer={x:p.x,y:p.y,down:true};S.pressed=null;if(S.screen==='menu')return menuDown(p);if(S.screen==='loading')return;if(S.screen==='difficulty')return diffDown(p);if(S.screen==='rules')return rulesDown(p);if(S.screen==='gallery')return galleryDown(p);if(S.screen==='result')return resultDown(p);if(S.screen!=='game')return;let l=S.layout;if(hit(p,inf(l.home,8))){press('home',l.home);S.screen='menu';S.dragging=false;return}if(hit(p,inf(l.galleryButton,8))){press('galleryTop',l.galleryButton);S.lastScreen='game';S.screen='gallery';S.dragging=false;return}if(S.mode==='bossFight'){if(hit(p,inf(l.bossButton,26,24))){press('bossSeal',l.bossButton);bossSeal()}return}if(S.mode!=='normal')return;if(hit(p,inf(l.sealButton,22,20))){press('seal',l.sealButton);sealClick();return}let z={x:l.door.x-46,y:l.door.y-26,w:l.door.w+92,h:l.door.h+52};if(hit(p,z)){S.dragging=true;S.dragX=p.x;S.dragDoor=S.door;S.snapTarget=null}}
function move(e){let p=ptr(e);S.pointer.x=p.x;S.pointer.y=p.y;if(S.screen==='rules'&&S.rulesDragging){e.preventDefault();S.rulesScroll=clamp(S.rulesStart+(S.rulesY-p.y),0,maxRules());return}if(S.screen==='gallery'&&S.galleryDragging){e.preventDefault();S.galleryScroll=clamp(S.galleryStart+(S.galleryY-p.y),0,maxGallery());return}if(!S.dragging||S.screen!=='game'||S.mode!=='normal')return;e.preventDefault();let l=S.layout,dx=S.dragX-p.x;S.door=clamp(S.dragDoor+dx/(l.door.w*.58),0,1)}
function up(e){let p=ptr(e);S.pointer={x:p.x,y:p.y,down:false};S.pressed=null;S.rulesDragging=false;S.galleryDragging=false;if(S.dragging){S.dragging=false;S.snapTarget=S.door>.46?1:0}}
canvas.addEventListener('pointerdown',down,{passive:false});canvas.addEventListener('pointermove',move,{passive:false});canvas.addEventListener('pointerup',up,{passive:false});canvas.addEventListener('pointercancel',up,{passive:false});canvas.addEventListener('wheel',e=>{if(S.screen==='rules'){e.preventDefault();S.rulesScroll=clamp(S.rulesScroll+e.deltaY,0,maxRules())}else if(S.screen==='gallery'){e.preventDefault();S.galleryScroll=clamp(S.galleryScroll+e.deltaY,0,maxGallery())}},{passive:false});
function menuBtns(){let l=S.layout,bw=Math.min(260,l.w*.68),bh=58,x=(l.w-bw)/2,y=l.h*.45;return{start:{x,y,w:bw,h:bh},rules:{x,y:y+76,w:bw,h:bh},gallery:{x,y:y+152,w:bw,h:bh},lang:{x:l.w-82,y:18,w:64,h:36}}}
function menuDown(p){let b=menuBtns();if(hit(p,inf(b.lang,8))){press('lang',b.lang);S.lang=S.lang==='zh'?'en':'zh';return}if(hit(p,inf(b.start,10))){press('start',b.start);beginLoading('difficulty',initialFiles())}else if(hit(p,inf(b.rules,10))){press('rules',b.rules);S.screen='rules'}else if(hit(p,inf(b.gallery,10))){press('gallery',b.gallery);S.lastScreen='menu';S.screen='gallery'}}
function diffDown(p){let l=S.layout,bw=Math.min(270,l.w*.72),x=(l.w-bw)/2,easy={x,y:l.h*.43,w:bw,h:70},hard={x,y:l.h*.43+94,w:bw,h:70},back={x:16,y:18,w:70,h:40};if(hit(p,inf(back,8))){press('back',back);S.screen='menu'}else if(hit(p,inf(easy,10))){press('easy',easy);startRun('easy')}else if(hit(p,inf(hard,10))){press('hard',hard);startRun('normal')}}
function rulesDown(p){let back={x:16,y:18,w:70,h:40};if(hit(p,inf(back,8))){press('back',back);S.screen='menu';return}let r=rulesRect();if(hit(p,r)){S.rulesDragging=true;S.rulesY=p.y;S.rulesStart=S.rulesScroll}}
function galleryDown(p){let l=S.layout,back={x:16,y:18,w:70,h:40};if(hit(p,inf(back,8))){press('back',back);S.screen=S.lastScreen==='game'?'game':'menu';return}let tabW=Math.min(146,(l.w-44)/2),g={x:18,y:78,w:tabW,h:42},pe={x:28+tabW,y:78,w:tabW,h:42};if(hit(p,g)){S.galleryTab='ghosts';S.galleryScroll=0;return}if(hit(p,pe)){S.galleryTab='people';S.galleryScroll=0;return}if(p.y>126){S.galleryDragging=true;S.galleryY=p.y;S.galleryStart=S.galleryScroll}}
function resultDown(p){let l=S.layout,bw=Math.min(260,l.w*.68),x=(l.w-bw)/2,a={x,y:l.h*.58,w:bw,h:58},h={x,y:l.h*.58+76,w:bw,h:58};if(hit(p,inf(a,10))){press('again',a);S.screen='difficulty'}else if(hit(p,inf(h,10))){press('homeResult',h);S.screen='menu'}}
function clear(){let l=S.layout;ctx.clearRect(0,0,l.w,l.h);ctx.fillStyle='#fff';ctx.fillRect(0,0,l.w,l.h)}function draw(){clear();({menu:drawMenu,loading:drawLoading,difficulty:drawDiff,rules:drawRules,gallery:drawGallery,game:drawGame,result:drawResult}[S.screen]||drawMenu)()}
function bg(){let l=S.layout;ctx.fillStyle='#fff';ctx.fillRect(0,0,l.w,l.h)}
function drawMenu(){let l=S.layout,b=menuBtns();bg();homeFires();ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#fffdf6';rr(l.w/2-138,l.h*.18,276,126,24,1,1,5);ctx.fillStyle='#111';ctx.font=en()?'900 31px system-ui':'900 43px system-ui';ctx.fillText(en()?'TIMID EXORCIST':'胆小除魔师',l.w/2,l.h*.24);ctx.font='700 15px system-ui';ctx.fillText(ui('无限长廊，开门识别异常','Endless corridor. Open and decide.'),l.w/2,l.h*.305);ctx.font='700 13px system-ui';ctx.fillText(VERSION,l.w/2,l.h*.36);ctx.restore();mini(b.lang,en()?'中':'EN','lang');btn(b.start,en()?'Start':'开始游戏','','start');btn(b.rules,en()?'Rules':'游戏规则','','rules');btn(b.gallery,en()?`Archive ${collect()}`:`图鉴 ${collect()}`,'','gallery')}
function drawLoading(){let l=S.layout,p=progress(S.loadingFiles),tp=clamp(S.loadingElapsed/.55,0,1),r=clamp(Math.max(p.loaded*.92,tp*.36),0,1);bg();homeFires();ctx.save();ctx.fillStyle='#fffdf6';rr(l.w*.09,l.h*.31,l.w*.82,210,24,1,1,5);ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 28px system-ui';ctx.fillText(ui('正在点香……','Lighting incense...'),l.w/2,l.h*.31+54);ctx.font='700 13px system-ui';ctx.fillText(ui('正在准备长廊和符咒','Preparing corridor and seals'),l.w/2,l.h*.31+90);bar(l.w*.18,l.h*.31+124,l.w*.64,18,r);ctx.font='700 12px system-ui';ctx.fillText(ui(`素材 ${p.count}/${p.total}`,`Assets ${p.count}/${p.total}`),l.w/2,l.h*.31+166);ctx.restore()}
function drawDiff(){let l=S.layout,bw=Math.min(270,l.w*.72),x=(l.w-bw)/2;bg();back();title(ui('选择难度','Select Difficulty'),ui('简单版会降低瘦子鬼速度','Easy mode slows down thin ghosts'));btn({x,y:l.h*.43,w:bw,h:70},ui('简单版','Easy'),ui('新手 / 瘦子鬼更慢','Beginner / slower thin ghosts'),'easy');btn({x,y:l.h*.43+94,w:bw,h:70},ui('困难版','Hard'),ui('原始速度 / 更紧张','Original speed / tense'),'hard')}
function rulesLines(){return en()?['1. Drag the wooden door left to peek inside. Release to snap open or closed.','2. Each cleared door slides away sideways. A new door enters from the corridor.','3. Ghosts have different speeds. If you stare too long, they will burst out.','4. For ghosts, close the door first, then tap Seal.','5. If there is a person or an empty room, open the door wide enough to pass.','6. Sealing the Nine-tailed Fox opens Ghost Eye for 10 seconds.','7. Bosses appear near every 25th door. Confirm, close, then seal rapidly.','8. The Archive records ghosts and people you have seen.']:['1. 拖动红木滑门向左开门，松手后会自动吸附开/关。','2. 判断成功后，当前门位会横向滑走，新的门从长廊另一侧滑入。','3. 鬼有快慢差异，看太久会一段段逼近，危险值满了就会冲出来。','4. 普通鬼需要先关门，再点击封印。','5. 门后是人物或空房间时，开到足够大即可通过；乱封会直接失败。','6. 封印九尾狐后开启10秒鬼眼，门会变透明。','7. 每25关附近会出现Boss：先开门确认，再关门疯狂贴符。','8. 图鉴会记录见过的鬼和人物，可以上下滑动查看。']}
function rulesRect(){let l=S.layout;return{x:l.w*.07,y:l.h*.31,w:l.w*.86,h:l.h*.55}}function maxRules(){let r=rulesRect();ctx.save();ctx.font=`${en()?12:14}px system-ui`;let h=measure(rulesLines(),r.w-36,en()?17:22,7);ctx.restore();return Math.max(0,h-(r.h-42))}
function drawRules(){bg();back();title(ui('游戏规则','Rules'),ui('不要乱封，也不要看太久','Observe first. Seal only when sure.'));S.rulesScroll=clamp(S.rulesScroll,0,maxRules());scrollText(rulesLines(),rulesRect(),S.rulesScroll)}
function galMetric(){let l=S.layout,list=S.galleryTab==='ghosts'?GHOSTS:PEOPLE,cols=en()?2:3,gap=12,cw=(l.w-32-gap*(cols-1))/cols,ch=en()?Math.min(218,cw*1.42):Math.min(182,cw*1.78),startY=138,rows=Math.ceil(list.length/cols),contentH=rows*(ch+14)-14,viewH=l.h-startY-18;return{l,list,cols,gap,cw,ch,startY,contentH,viewH}}
function maxGallery(){let m=galMetric();return Math.max(0,m.contentH-m.viewH)}
function drawGallery(){let m=galMetric(),l=m.l;S.galleryScroll=clamp(S.galleryScroll,0,maxGallery());bg();back();ctx.fillStyle='#111';ctx.font='900 30px system-ui';ctx.textAlign='center';ctx.fillText(ui('图鉴','Archive'),l.w/2,45);let tw=Math.min(146,(l.w-44)/2),gt={x:18,y:78,w:tw,h:42},pt={x:28+tw,y:78,w:tw,h:42};tab(gt,`${ui('鬼图鉴','Ghosts')} ${seenG()}/${GHOSTS.length}`,S.galleryTab==='ghosts');tab(pt,`${ui('人物图鉴','People')} ${seenP()}/${PEOPLE.length}`,S.galleryTab==='people');let seenMap=S.galleryTab==='ghosts'?S.save.ghosts:S.save.people;ctx.save();ctx.beginPath();ctx.rect(0,m.startY-4,l.w,l.h-m.startY+4);ctx.clip();m.list.forEach((it,i)=>{let col=i%m.cols,row=Math.floor(i/m.cols),x=16+col*(m.cw+m.gap),y=m.startY+row*(m.ch+14)-S.galleryScroll;if(y>l.h||y+m.ch<m.startY-10)return;card({x,y,w:m.cw,h:m.ch},it,!!seenMap[it.name])});ctx.restore()}
function drawResult(){let l=S.layout;bg();ctx.save();ctx.textAlign='center';ctx.fillStyle='#fffdf6';rr(l.w*.08,l.h*.22,l.w*.84,l.h*.28,24,1,1,5);ctx.fillStyle='#111';ctx.font='900 38px system-ui';ctx.fillText(ui('游戏结束','Game Over'),l.w/2,l.h*.30);ctx.font='700 17px system-ui';wrap(resultTxt(S.resultReason),l.w/2,l.h*.365,l.w*.72,24,'center');ctx.font='800 16px system-ui';ctx.fillText(ui(`本次到达：第 ${S.room} 门`,`Reached Door ${S.room}`),l.w/2,l.h*.445);ctx.fillText(ui(`最高纪录：第 ${S.save.bestRoom||1} 门`,`Best: Door ${S.save.bestRoom||1}`),l.w/2,l.h*.478);ctx.restore();let bw=Math.min(260,l.w*.68),x=(l.w-bw)/2;btn({x,y:l.h*.58,w:bw,h:58},ui('再来一局','Try Again'),'','again');btn({x,y:l.h*.58+76,w:bw,h:58},ui('返回主页','Home'),'','homeResult')}
function resultTxt(z){if(!en())return z;return{'门开太久，鬼冲出来了':'The door stayed open too long. The ghost escaped.','封错了，人家只是普通人':'Wrong seal. That was just a normal person.','封错了，这间房是空的':'Wrong seal. This room was empty.','强制Boss战失败，Boss冲出来了':'Forced boss fight failed. The boss broke out.'}[z]||z||'Run ended.'}
function toastTxt(z){if(!en())return z;return{'Boss开始顶门！':'Boss is forcing the door!','先开门确认':'Open the door to confirm first.','关门后才能开始贴符':'Close the door before sealing.','先把门关上':'Close the door first.','鬼眼开启：10秒透视':'Ghost Eye: 10 seconds of vision.','符咒贴上去了':'Seal placed.','Boss已封印，进入下一大关':'Boss sealed. Next stage unlocked.','Boss逃走了':'Boss escaped.'}[z]||z}
function drawGame(){let l=S.layout;ctx.save();ctx.beginPath();ctx.rect(0,l.topH,l.w,l.h-l.topH);ctx.clip();let sh=shake();if(sh>0)ctx.translate(Math.sin(S.t*52)*sh+Math.sin(S.t*19)*sh*.45,Math.cos(S.t*47)*sh*.45);if(S.mode==='corridorTransition'){corridor(S.corridorOffset,S.content,S.door);corridor(S.corridorOffset+l.w,S.nextContent,0)}else corridor(0,S.content,S.door);ctx.restore();topUI();eyeFx();bottom();drawToast()}
function shake(){if(S.mode==='sealSuccess')return 4*clamp(1-S.sealFlash/.62,0,1);if(S.mode==='bossFight')return 1.5+Math.max(0,S.door-.65)*5;if(S.danger>.78)return 3.2;if(S.danger>.55)return 1.6;return 0}
function corridor(off,c,doorProg){let l=S.layout;ctx.save();ctx.translate(off,0);corridorBg();roomBack(l.hole);content(c,l.door,l.hole);wall(l.hole);frame(l.hole);bossGlow(c,l.hole);doorPanel(l.door,doorProg);talismans(c,l.door,doorProg);sealGlow();danger();ctx.restore()}
function corridorBg(){let l=S.layout,base=l.door.y+l.door.h+2;ctx.fillStyle='#fbfbf7';ctx.fillRect(-4,l.topH,l.w+8,l.h-l.topH);ctx.strokeStyle='rgba(0,0,0,.12)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,base);ctx.lineTo(l.w,base);ctx.stroke();ctx.lineWidth=1.2;for(let i=-1;i<8;i++){let x=i*(l.w/6)+(S.room%2)*12;ctx.beginPath();ctx.moveTo(x,base);ctx.lineTo(x+l.w*.18,l.h-l.bottomH*.2);ctx.stroke()}for(let i=1;i<=5;i++){let y=lerp(base,l.h-l.bottomH*.2,i/6);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(l.w,y);ctx.stroke()}}
function roomBack(h){ctx.save();rpath(h.x+4,h.y+4,h.w-8,h.h-8,8);ctx.clip();let g=ctx.createLinearGradient(0,h.y,0,h.y+h.h);g.addColorStop(0,'#f8f6ee');g.addColorStop(.58,'#fffdf7');g.addColorStop(1,'#eee7dc');ctx.fillStyle=g;ctx.fillRect(h.x,h.y,h.w,h.h);let fy=h.y+h.h*.74;ctx.strokeStyle='rgba(0,0,0,.16)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(h.x,fy);ctx.lineTo(h.x+h.w,fy);ctx.stroke();ctx.lineWidth=1;for(let i=1;i<=4;i++){let y=lerp(fy,h.y+h.h,i/5);ctx.beginPath();ctx.moveTo(h.x,y);ctx.lineTo(h.x+h.w,y);ctx.stroke()}let cx=h.x+h.w/2;for(let i=-2;i<=2;i++){ctx.beginPath();ctx.moveTo(cx+i*h.w*.16,fy);ctx.lineTo(cx+i*h.w*.36,h.y+h.h);ctx.stroke()}ctx.restore()}
function content(c,d,h){if(!c)return;let floor=h.y+h.h*.94;ctx.save();ctx.beginPath();ctx.rect(h.x+5,h.y+5,h.w-10,h.h-10);ctx.clip();if(c.type==='person')character(c.person,d.x+d.w/2,floor,d.h*.60,'person',1);else if(c.type==='ghost'){let n=c.ghosts.length,ap=c===S.content?approach():0,sc=1+ap*.68,bh=d.h*(n===1?.60:n===2?.49:.40),spread=d.w*(n===1?0:n===2?.25:.28);c.ghosts.forEach((g,i)=>{let off=n===1?0:(i-(n-1)/2)*spread,hide=g.name==='九尾狐'?-d.w*.24:0,x=d.x+d.w/2+off+hide,gh=bh*sc;character(g,x,floor,bh,'ghost',sc);fires(g,x,floor-gh*.58,gh,Math.max(1,g.fire||1),i)})}else if(c.type==='boss'){let ap=S.mode==='bossFight'&&c===S.content?Math.floor(S.door*8)/8:0,sc=S.mode==='bossFight'&&c===S.content?1+ap*.45:1;character(c.bossGhost,d.x+d.w/2,floor+d.h*.04,d.h*.76,'boss',sc);fires(c.bossGhost,d.x+d.w/2,floor-d.h*.52,d.h*.80,(c.bossGhost.fire||3)+2,9)}ctx.restore()}
function wall(h){let l=S.layout;ctx.fillStyle='#fff';ctx.fillRect(0,l.topH,Math.max(0,h.x),l.h-l.topH);ctx.fillRect(h.x+h.w,l.topH,Math.max(0,l.w-(h.x+h.w)),l.h-l.topH);ctx.fillRect(h.x,l.topH,h.w,Math.max(0,h.y-l.topH));ctx.fillRect(h.x,h.y+h.h,h.w,Math.max(0,l.h-(h.y+h.h)));ctx.strokeStyle='rgba(0,0,0,.12)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,h.y+h.h);ctx.lineTo(l.w,h.y+h.h);ctx.stroke()}
function frame(h){let r=10;ctx.strokeStyle='#111';ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(h.x,h.y+h.h);ctx.lineTo(h.x,h.y+r);ctx.quadraticCurveTo(h.x,h.y,h.x+r,h.y);ctx.lineTo(h.x+h.w-r,h.y);ctx.quadraticCurveTo(h.x+h.w,h.y,h.x+h.w,h.y+r);ctx.lineTo(h.x+h.w,h.y+h.h);ctx.stroke();ctx.lineWidth=2.6;ctx.beginPath();ctx.moveTo(h.x+1,h.y+h.h);ctx.lineTo(h.x+h.w-1,h.y+h.h);ctx.stroke()}
function doorAlpha(){return S.ghostEye>0&&S.mode==='normal'?.4:1}
function doorPanel(d,p){let a=doorAlpha(),slide=d.w*.96*p,x=d.x-slide,y=d.y,w=d.w,h=d.h;ctx.save();ctx.globalAlpha=a;let g=ctx.createLinearGradient(x,y,x+w,y);['#6f3523','#8b4a30','#a35b3b','#7b3d29','#5f2b1c'].forEach((c,i)=>g.addColorStop([0,.18,.52,.84,1][i],c));ctx.fillStyle=g;ctx.strokeStyle='#111';ctx.lineWidth=5;rr(x,y,w,h,10,1,1,5);ctx.save();rpath(x+3,y+3,w-6,h-6,8);ctx.clip();let n=Math.max(6,Math.floor(w/22));ctx.strokeStyle='rgba(255,255,255,.15)';ctx.lineWidth=1;for(let i=1;i<n;i++){let xx=x+(w/n)*i+Math.sin(i*1.7)*1.2;ctx.beginPath();ctx.moveTo(xx,y+8);ctx.bezierCurveTo(xx+Math.sin(i)*1.5,y+h*.3,xx-Math.cos(i)*1.3,y+h*.65,xx+Math.sin(i*2.1),y+h-8);ctx.stroke()}ctx.strokeStyle='rgba(0,0,0,.14)';ctx.lineWidth=1.3;for(let i=1;i<n;i+=2){let xx=x+(w/n)*i;ctx.beginPath();ctx.moveTo(xx,y+6);ctx.lineTo(xx,y+h-6);ctx.stroke()}ctx.restore();ctx.lineWidth=2.2;ctx.strokeStyle='rgba(255,255,255,.22)';rr(x+13,y+13,w-26,h-26,8,0,1,2.2);ctx.globalAlpha=a*.12;ctx.fillStyle='#fff';rr(x+13,y+13,Math.max(22,w*.12),h-26,8,1,0);ctx.globalAlpha=a;ctx.strokeStyle='rgba(0,0,0,.68)';ctx.lineWidth=2.6;ctx.beginPath();ctx.moveTo(x+1,y+h);ctx.lineTo(x+w-1,y+h);ctx.stroke();ctx.restore()}
function actualDoor(d,p){return{x:d.x-d.w*.96*p,y:d.y,w:d.w,h:d.h}}
function bossGlow(c,h){if(!c||c.type!=='boss')return;let pulse=.5+Math.sin(S.t*12)*.5,hp=1-(c.hits||0)/c.cfg.seals,fast=hp<.3?1:.35;ctx.save();ctx.globalAlpha=S.mode==='bossFight'?.48+pulse*fast*.24:.34;let g=ctx.createRadialGradient(h.x+h.w/2,h.y+h.h/2,10,h.x+h.w/2,h.y+h.h/2,h.w*.82);g.addColorStop(0,'rgba(255,28,10,.95)');g.addColorStop(.48,'rgba(255,28,10,.28)');g.addColorStop(1,'rgba(255,28,10,0)');ctx.fillStyle=g;ctx.fillRect(h.x-80,h.y-80,h.w+160,h.h+160);ctx.restore()}
function fires(def,cx,cy,bh,count,seed=0){ctx.save();let base=GHOSTS.findIndex(g=>g.name===def.name),safe=base>=0?base:seed;for(let i=0;i<clamp(count,1,7);i++){let side=i%2===0?-1:1,lay=Math.floor(i/2),x=cx+side*bh*(.22+lay*.08)+Math.sin(S.t*(1.1+i*.17)+safe*.9+i)*bh*.035,y=cy-bh*(.04+lay*.035)+Math.sin(S.t*(1.7+i*.23)+i*1.8)*bh*.045,sz=bh*(.14+(i%3)*.022),im=img(FIRE[(safe+i)%FIRE.length]),pulse=.72+Math.sin(S.t*3.2+i)*.15;ctx.globalAlpha=clamp(.72+pulse*.24,.58,1);if(im)ctx.drawImage(im,x-sz/2,y-sz*.65,sz,sz*1.28);else codeFire(x,y,sz,pulse)}ctx.restore()}
function codeFire(x,y,s,p){ctx.save();ctx.translate(x,y);ctx.scale(1,1+p*.15);let g=ctx.createRadialGradient(0,0,s*.05,0,0,s*.72);g.addColorStop(0,'rgba(255,255,220,.95)');g.addColorStop(.34,'rgba(95,255,160,.72)');g.addColorStop(1,'rgba(35,220,120,0)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,-s*.78);ctx.bezierCurveTo(s*.45,-s*.28,s*.38,s*.32,0,s*.48);ctx.bezierCurveTo(-s*.42,s*.18,-s*.40,-s*.28,0,-s*.78);ctx.fill();ctx.restore()}
function character(def,x,floor,target,kind,scale=1){let im=img(def.file),h=target*scale*(def.scale||1),asp=im?im.naturalWidth/im.naturalHeight:.62,w=h*asp,y=floor-h;ctx.save();if(kind==='boss'){let p=.5+Math.sin(S.t*14)*.5;ctx.shadowColor='rgba(255,0,0,.85)';ctx.shadowBlur=24+p*16}if(im)ctx.drawImage(im,x-w/2,y,w,h);else fallback(def.name||nm(def),x,y,w,h,kind);ctx.restore()}
function fallback(name,x,y,w,h,kind){let person=kind==='person',boss=kind==='boss';ctx.fillStyle=person?'#fffdf6':'#111';ctx.strokeStyle=person?'#111':'#fffdf6';ctx.lineWidth=boss?5:4;ctx.beginPath();ctx.arc(x,y+h*.16,w*.20,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(x,y+h*.3);ctx.bezierCurveTo(x+w*.34,y+h*.35,x+w*.32,y+h*.7,x,y+h*.82);ctx.bezierCurveTo(x-w*.34,y+h*.7,x-w*.32,y+h*.35,x,y+h*.3);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(x-w*.15,y+h*.82);ctx.lineTo(x-w*.26,y+h);ctx.moveTo(x+w*.15,y+h*.82);ctx.lineTo(x+w*.26,y+h);ctx.stroke();ctx.fillStyle=person?'#111':'#fffdf6';ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.fillText(String(name||'').slice(0,4),x,y+h*.55)}
function talismans(c,d,p){if(!c||!c.talismans)return;let dd=actualDoor(d,p);c.talismans.forEach(t=>{let age=S.t-(t.born||S.t),a=1;if(S.mode==='sealSuccess'&&age>.15)a=clamp(1-S.sealFlash/.62,0,1);paper(dd.x+dd.w*t.rx,dd.y+dd.h*t.ry,dd.w*.25*t.scale,dd.h*.118*t.scale,t.rot,a)})}
function paper(x,y,w,h,rot,a){ctx.save();ctx.translate(x,y);ctx.rotate(rot);ctx.globalAlpha=a;let ww=Math.max(w*.72,34),hh=Math.max(h*1.12,72);ctx.fillStyle='#f7d85a';ctx.strokeStyle='#111';ctx.lineWidth=3;rr(-ww/2,-hh/2,ww,hh,5,1,1,3);ctx.strokeStyle='#b11616';ctx.lineWidth=2;rr(-ww/2+5,-hh/2+6,ww-10,hh-12,3,0,1,2);ctx.fillStyle='#b11616';ctx.font=`900 ${Math.max(18,ww*.48)}px serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('封',0,-hh*.2);ctx.font=`900 ${Math.max(14,ww*.36)}px serif`;ctx.fillText('印',0,hh*.18);ctx.restore()}
function sealGlow(){if(S.mode!=='sealSuccess')return;let l=S.layout,a=clamp(1-S.sealFlash/.62,0,1);ctx.save();ctx.globalAlpha=a*.72;ctx.strokeStyle='#ffe243';ctx.lineWidth=12;rr(l.hole.x-8,l.hole.y-8,l.hole.w+16,l.hole.h+16,18,0,1,12);ctx.globalAlpha=a*.26;ctx.fillStyle='#fff';ctx.fillRect(0,l.topH,l.w,l.h-l.topH);ctx.globalAlpha=a*.35;ctx.fillStyle='#ffe243';ctx.fillRect(l.hole.x-26,l.hole.y-26,l.hole.w+52,l.hole.h+52);ctx.restore()}
function danger(){if(S.danger<=.02||S.mode!=='normal')return;let l=S.layout;ctx.save();ctx.globalAlpha=clamp(S.danger,0,1)*.46;let g=ctx.createRadialGradient(l.w/2,l.h/2,l.w*.15,l.w/2,l.h/2,l.w*.72);g.addColorStop(0,'rgba(255,0,0,0)');g.addColorStop(1,'rgba(255,0,0,.9)');ctx.fillStyle=g;ctx.fillRect(0,l.topH,l.w,l.h-l.topH);ctx.restore();if(S.danger>.78){ctx.save();ctx.globalAlpha=(S.danger-.78)*2.3;ctx.fillStyle='#111';ctx.font='900 18px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(ui('太久了……','Too long...'),l.w/2,l.topH+40);ctx.restore()}}
function topUI(){let l=S.layout,p=prog();ctx.save();ctx.fillStyle='#fff';ctx.fillRect(0,0,l.w,l.topH);ctx.strokeStyle='#111';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,l.topH-2);ctx.lineTo(l.w,l.topH-2);ctx.stroke();mini(l.home,ui('主页','Home'),'home');mini(l.galleryButton,ui('图鉴','Archive'),'galleryTop');ctx.fillStyle='#111';ctx.textAlign='left';ctx.textBaseline='middle';ctx.font='900 16px system-ui';ctx.fillText(ui(`第 ${S.room} 门`,`Door ${S.room}`),86,22);ctx.font='700 11px system-ui';let df=S.difficulty==='easy'?ui('简单','Easy'):ui('困难','Hard');ctx.fillText(ui(`难度 ${df}  最高 ${S.save.bestRoom||1}`,`${df}  Best ${S.save.bestRoom||1}`),86,43);ctx.fillText(ui(`进度 ${p.index}/25  Boss：${p.boss.name}`,`Progress ${p.index}/25  Boss: ${nm(p.boss)}`),86,63);bar(86,l.topH-13,Math.max(80,l.w-188),6,p.ratio);ctx.textAlign='right';ctx.font='700 10px system-ui';ctx.fillText(collect(),l.w-10,64);if(S.ghostEye>0){ctx.font='800 11px system-ui';ctx.fillText(ui(`鬼眼 ${Math.ceil(S.ghostEye)}s`,`Eye ${Math.ceil(S.ghostEye)}s`),l.w-10,l.topH-16)}if(S.mode==='bossFight'&&S.content&&S.content.type==='boss')bossHP();ctx.restore()}
function bossHP(){let l=S.layout,c=S.content,r=clamp(1-c.hits/c.cfg.seals,0,1),x=86,y=l.topH-25,w=l.w-172,h=9;ctx.fillStyle='#fff';ctx.strokeStyle='#111';ctx.lineWidth=2;rr(x,y,w,h,4,1,1,2);ctx.fillStyle=r<.3?'#ff3b20':'#111';rr(x,y,w*r,h,4,1,0)}
function bottom(){let l=S.layout;if(S.mode==='corridorTransition'||S.mode==='sealSuccess')return;if(S.mode==='bossFight')return bossBtn(l.bossButton);sealBtn(l.sealButton)}
function sealBtn(r){let im=img('封印按钮.png');pressDraw(r,'seal',()=>{if(im){let asp=im.naturalWidth/im.naturalHeight,dh=r.h,dw=dh*asp;if(dw>r.w){dw=r.w;dh=dw/asp}ctx.drawImage(im,r.x+(r.w-dw)/2,r.y+(r.h-dh)/2,dw,dh)}else{ctx.fillStyle='#fff06d';ctx.strokeStyle='#111';ctx.lineWidth=4;rr(r.x,r.y,r.w,r.h,15,1,1,4);ctx.fillStyle='#111';ctx.font='900 25px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('封 印',r.x+r.w/2,r.y+r.h/2)}})}
function bossBtn(r){ctx.save();let beat=1+Math.sin(S.t*18)*.025,pr=isPress('bossSeal')?.94:1,cx=r.x+r.w/2,cy=r.y+r.h/2;ctx.translate(cx,cy);ctx.scale(beat*pr,beat*pr);ctx.globalAlpha=isPress('bossSeal')?.86:1;ctx.fillStyle='#fff06d';ctx.strokeStyle='#111';ctx.lineWidth=5;rr(-r.w/2,-r.h/2,r.w,r.h,18,1,1,5);ctx.fillStyle='#111';ctx.font='900 24px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(ui('疯狂贴封印！','Seal Fast!'),0,0);ctx.restore()}
function eyeFx(){if(S.eyeFx<=0)return;let l=S.layout,p=clamp(S.eyeFx/1.05,0,1);ctx.save();ctx.globalAlpha=p*.85;ctx.fillStyle='rgba(255,255,255,.55)';ctx.fillRect(0,l.topH,l.w,l.h-l.topH);ctx.translate(l.w/2,l.topH+(l.h-l.topH)*.42);ctx.strokeStyle='rgba(0,0,0,.75)';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-86,0);ctx.quadraticCurveTo(0,-52,86,0);ctx.quadraticCurveTo(0,52,-86,0);ctx.stroke();ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(0,0,8,0,Math.PI*2);ctx.fillStyle='rgba(0,0,0,.78)';ctx.fill();ctx.restore()}
function drawToast(){if(!S.toast)return;let l=S.layout;ctx.save();ctx.globalAlpha=clamp(S.toast.time,0,1);ctx.fillStyle='#111';ctx.strokeStyle='#fffdf6';ctx.lineWidth=3;let w=Math.min(l.w*.78,300),h=42,x=(l.w-w)/2,y=l.topH+12;rr(x,y,w,h,18,1,1,3);ctx.fillStyle='#fffdf6';ctx.font='800 14px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(toastTxt(S.toast.text),l.w/2,y+h/2);ctx.restore()}
function homeFires(){let l=S.layout;ctx.save();for(let i=0;i<9;i++){let bx=(.08+(i%5)*.21)*l.w,by=(.14+Math.floor(i/5)*.55+(i%2)*.08)*l.h,x=bx+Math.sin(S.t*(.8+i*.06)+i)*16,y=by+Math.cos(S.t*(1+i*.08)+i*1.7)*18,sz=Math.max(34,Math.min(58,l.w*(.09+(i%3)*.012))),im=img(FIRE[i%FIRE.length]);ctx.globalAlpha=.34+Math.sin(S.t*2+i)*.08;if(im)ctx.drawImage(im,x-sz/2,y-sz*.65,sz,sz*1.28);else codeFire(x,y,sz,.8)}ctx.restore()}
function title(t,s){let l=S.layout;ctx.fillStyle='#fffdf6';rr(l.w*.08,l.h*.18,l.w*.84,104,22,1,1,5);ctx.fillStyle='#111';ctx.textAlign='center';ctx.font='900 34px system-ui';ctx.fillText(t,l.w/2,l.h*.18+45);ctx.font='700 14px system-ui';ctx.fillText(s,l.w/2,l.h*.18+76)}
function back(){mini({x:16,y:18,w:70,h:40},S.screen==='gallery'&&S.lastScreen==='game'?ui('返回游戏','Back'):ui('返回','Back'),'back')}
function pressDraw(r,id,fn){ctx.save();if(isPress(id)){ctx.translate(r.x+r.w/2,r.y+r.h/2);ctx.scale(.94,.94);ctx.translate(-(r.x+r.w/2),-(r.y+r.h/2));ctx.globalAlpha*=.86}fn();ctx.restore()}
function mini(r,text,id=''){pressDraw(r,id,()=>{ctx.fillStyle='#fffdf6';ctx.strokeStyle='#111';ctx.lineWidth=3;rr(r.x,r.y,r.w,r.h,12,1,1,3);ctx.fillStyle='#111';ctx.font='800 14px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,r.x+r.w/2,r.y+r.h/2)})}
function btn(r,t,sub='',id=''){pressDraw(r,id,()=>{ctx.fillStyle='#fffdf6';ctx.strokeStyle='#111';ctx.lineWidth=5;rr(r.x,r.y,r.w,r.h,18,1,1,5);ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=sub?'900 22px system-ui':'900 24px system-ui';ctx.fillText(t,r.x+r.w/2,r.y+r.h/2-(sub?10:0));if(sub){ctx.font='700 12px system-ui';ctx.fillText(sub,r.x+r.w/2,r.y+r.h/2+18)}})}
function tab(r,text,act){ctx.fillStyle=act?'#111':'#fffdf6';ctx.strokeStyle='#111';ctx.lineWidth=3;rr(r.x,r.y,r.w,r.h,13,1,1,3);ctx.fillStyle=act?'#fffdf6':'#111';ctx.font='800 13px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,r.x+r.w/2,r.y+r.h/2)}
function card(r,it,seen){ctx.save();ctx.fillStyle='#fffdf6';ctx.strokeStyle='#111';ctx.lineWidth=3;rr(r.x,r.y,r.w,r.h,16,1,1,3);let box={x:r.x+6,y:r.y+6,w:r.w-12,h:r.h-(en()?78:66)};ctx.beginPath();ctx.rect(box.x,box.y,box.w,box.h);ctx.clip();seen?cardImg(it,box):egg(box,r.w);ctx.restore();ctx.save();ctx.beginPath();ctx.rect(r.x+6,r.y+r.h-(en()?72:58),r.w-12,en()?68:54);ctx.clip();ctx.fillStyle='#111';ctx.textAlign='center';ctx.textBaseline='top';ctx.font='800 12px system-ui';ctx.fillText(seen?nm(it):ui('？？？','???'),r.x+r.w/2,r.y+r.h-(en()?70:56));ctx.font=`${en()?9.5:10}px system-ui`;wrap(seen?ds(it):ui('尚未记录','Not recorded yet'),r.x+r.w/2,r.y+r.h-(en()?52:38),r.w-14,en()?11:12,'center');ctx.restore()}
function egg(b,cw){let cx=b.x+b.w/2,cy=b.y+b.h*.52,rx=Math.min(b.w*.24,b.h*.28),ry=Math.min(b.h*.32,b.w*.38);ctx.fillStyle='#111';ctx.globalAlpha=.92;ctx.beginPath();ctx.ellipse(cx,cy,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.font=`900 ${Math.max(24,cw*.30)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=5;ctx.strokeStyle='#fffdf6';ctx.fillStyle='#111';ctx.strokeText('?',cx,cy);ctx.fillText('?',cx,cy)}
function cardImg(it,b){let im=img(it.file);if(im){let asp=im.naturalWidth/im.naturalHeight,dh=b.h*.96,dw=dh*asp;if(dw>b.w*.95){dw=b.w*.95;dh=dw/asp}ctx.drawImage(im,b.x+b.w/2-dw/2,b.y+b.h-dh,dw,dh)}else fallback(it.name,b.x+b.w/2,b.y+b.h*.08,b.w*.56,b.h*.86,S.galleryTab==='people'?'person':'ghost')}
function bar(x,y,w,h,r){ctx.fillStyle='#fff';ctx.strokeStyle='#111';ctx.lineWidth=h>10?3:2;rr(x,y,w,h,h/2,1,1,ctx.lineWidth);ctx.fillStyle='#111';rr(x+3,y+3,Math.max(0,(w-6)*clamp(r,0,1)),h-6,(h-6)/2,1,0)}
function scrollText(lines,r,scroll){ctx.fillStyle='#fffdf6';ctx.strokeStyle='#111';ctx.lineWidth=4;rr(r.x,r.y,r.w,r.h,18,1,1,4);ctx.save();ctx.beginPath();ctx.rect(r.x+12,r.y+14,r.w-28,r.h-28);ctx.clip();ctx.fillStyle='#111';ctx.font=`${en()?12:14}px system-ui`;ctx.textAlign='left';ctx.textBaseline='top';let lh=en()?17:22,yy=r.y+20-scroll;lines.forEach(line=>{yy=wrap(line,r.x+18,yy,r.w-42,lh,'left')+7});ctx.restore()}
function measure(lines,w,lh,gap=0){let total=0;lines.forEach(line=>total+=countLines(line,w)*lh+gap);return total}function countLines(t,w){let toks=tokens(t),line='',c=1;toks.forEach(tok=>{let test=line+tok;if(ctx.measureText(test).width>w&&line.trim()){line=tok.trimStart?tok.trimStart():tok;c++}else line=test});return c}
function collect(){return`${seenG()+seenP()}/${GHOSTS.length+PEOPLE.length}`}function seenG(){return GHOSTS.filter(g=>S.save.ghosts[g.name]).length}function seenP(){return PEOPLE.filter(p=>S.save.people[p.name]).length}
function tokens(t){let s=String(t);return /[A-Za-z]/.test(s)&&/\s/.test(s)?s.split(/(\s+)/).filter(Boolean):s.split('')}
function wrap(text,x,y,w,lh,align='left'){ctx.save();ctx.textAlign=align;let toks=tokens(text),line='',yy=y;toks.forEach(tok=>{let test=line+tok;if(ctx.measureText(test).width>w&&line.trim()){ctx.fillText(line.trimEnd?line.trimEnd():line,x,yy);line=tok.trimStart?tok.trimStart():tok;yy+=lh}else line=test});if(line)ctx.fillText(line.trimEnd?line.trimEnd():line,x,yy);ctx.restore();return yy+lh}
function rpath(x,y,w,h,r){let rr=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+rr,y);ctx.lineTo(x+w-rr,y);ctx.quadraticCurveTo(x+w,y,x+w,y+rr);ctx.lineTo(x+w,y+h-rr);ctx.quadraticCurveTo(x+w,y+h,x+w-rr,y+h);ctx.lineTo(x+rr,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-rr);ctx.lineTo(x,y+rr);ctx.quadraticCurveTo(x,y,x+rr,y);ctx.closePath()}
function rr(x,y,w,h,r,fill,stroke,lw=1){rpath(x,y,w,h,r);if(fill)ctx.fill();if(stroke){let old=ctx.lineWidth;ctx.lineWidth=lw;ctx.stroke();ctx.lineWidth=old}}
let last=performance.now();function loop(now){let dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
